### PR TITLE
Bugs/30

### PR DESCRIPTION
**Pull request by frantsao**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

* Fixed prom2teams requierements
* Updated prom2teams default version
* Updated test requirements

### Benefits

* Bugfixes
* Security fixes
### Possible Drawbacks
N/A

### Applicable Issues

#30

### CODE REVIEW

**Review by vicsufer — APPROVED** [review]

**Comment by ablancolopez** [comment]
changelog should be updated and maybe the destination branch should be changed :)

**Review by ablancolopez — APPROVED** [review]

**Comment by vicsufer** [comment]
Could your add this fragment under the noficication sections in 'travis.yml' ?
```
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
```

**Comment by ablancolopez** [comment]
And now that @vicsufer is raising the issue... could you also please add a .gitattributes file to the root dir? 😇 https://github.com/idealista/cookiecutter-ansible-role/blob/develop/%7B%7Bcookiecutter.app_name%7D%7D_role/%7B%25%20raw%20%25%7D.gitattributes%7B%25%20endraw%20%25%7D

**Comment by frantsao** [comment]
> changelog should be updated and maybe the destination branch should be changed :)

Ups... Done!

**Comment by frantsao** [comment]
> And now that @vicsufer is raising the issue... could you also please add a .gitattributes file to the root dir? innocent https://github.com/idealista/cookiecutter-ansible-role/blob/develop/%7B%7Bcookiecutter.app_name%7D%7D_role/%7B%25%20raw%20%25%7D.gitattributes%7B%25%20endraw%20%25%7D

Done!

**Comment by frantsao** [comment]
> Could your add this fragment under the noficication sections in 'travis.yml' ?
> 
> ```
>   email:
>     if: branch = main
>     on_success: change
>     on_failure: always
>     recipients:
>       - desarrollo.benders@idealista.com
> ```

Added!

**Review by xtianae7 — APPROVED** [review]

**Review by vicsufer — APPROVED** [review]

**Pull request merged**
